package Business;

/**
 * @date 15/10/2013
 * @author Paul Millar <D00152098>
 */

import java.util.Date;

public class Loan {

    /*--------------------------*/
    // **** BUSINESS RULES **** //
    /*--------------------------*/
    // (1) Loan ID is generated by the database, therefore it cannot be changed by the user.
    //     To help achieve this, we have made the setter method for this property to private.    
    // (2) A User cannot have more than one copy of a title out on loan. This will be checked prior to updating.
    // (3) Due date cannot be before date borrowed.
    // (4) Return date cannot be before date borrowed.
    
    private int     id;
    private int     userID;
    private String  titleIsbn; 
    private Date    dateBorrowed;
    private Date    dateDue;
    private Date    dateReturned;
    private String  titleName;
    private String  userName;
    private String userEmail;
    
    public static final String NORMALHEADER = String.format("%-13s\t%-60s\t%-18s\t%-18s\t%-20s",
                                                            "ISBN","Title","Out","Due", "");    
    public static final String LONGHEADER = String.format("%-13s\t%-60s\t%-20s\t%-18s\t%-18s\t%-20s",
                                                            "ISBN","Title","Borrower","Out","Due","");
    
    public Loan() {
        this.id = 0;
        this.dateBorrowed = new Date();
        this.dateDue = new Date();
        this.titleName = "";
        this.titleIsbn = "";
        this.userID = 0;
        this.userName = "";
    }

    public Loan(int id, int userID, String titleIsbn, Date dateBorrowed, Date dateDue, Date dateReturned) {
        this.id = id;
        this.userID = userID;
        this.titleIsbn = titleIsbn;
        this.dateBorrowed = dateBorrowed;
        this.dateDue = dateDue;
        this.dateReturned = dateReturned;
    }
    
    public Loan(int id, int userID, String titleIsbn, Date dateBorrowed, Date dateDue, Date dateReturned, String titleName, String userName, String userEmail) {
        this.id = id;
        this.userID = userID;
        this.titleIsbn = titleIsbn;
        this.dateBorrowed = dateBorrowed;
        this.dateDue = dateDue;
        this.dateReturned = dateReturned;
        this.titleName = titleName;
        this.userName = userName;
        this.userEmail = userEmail;
    }
    
    /**
     *
     * @return the unique identifier for this loan.
     */
    public int getId() {
        return this.id;
    }

    /**
     * Sets the unique identifier for this loan.
     * @param id
     */
    private void setId(int id) {
        this.id = id;
    }
        
    /**
     *
     * @return the date in which the title was loaned.
     */
    public Date getDateBorrowed() {
        return this.dateBorrowed;
    }

    /**
     * Sets the date in which the title was loaned.
     * @param dateBorrowed
     */
    public void setDateBorrowed(Date dateBorrowed) {
        this.dateBorrowed = dateBorrowed;
    }

    /**
     *
     * @return the date in which the title was/is due back.
     */
    public Date getDateDue() {
        return dateDue;
    }

    /**
     * Sets the date in which the title is due back.
     * @param dateDue
     */
    public void setDateDue(Date dateDue) {
        // Calculate the number of days between the date borrowed & the due date
        int dateDiff = (int)( dateDue.getTime() - this.dateBorrowed.getTime()) / (1000 * 60 * 60 * 24);
        
        if (dateDiff >= 0){
            this.dateDue = dateDue;
        } else {
            System.out.println("Due date cannot come before the date the title was borrowed on.");
        }
    }

    /**
     *
     * @return the date in which the title was returned.
     */
    public Date getDateReturned() {
        return dateReturned;
    }

    /**
     * Sets the date in which the title was returned.
     * @param dateReturned
     */
    public void setDateReturned(Date dateReturned) {
        // Calculate the number of days between the date borrowed & the due date
        int dateDiff = (int)( dateReturned.getTime() - this.dateBorrowed.getTime()) / (1000 * 60 * 60 * 24);
        
        if (dateDiff >= 0){
            this.dateReturned = dateReturned;
        } else {
            System.out.println("Return date cannot come before the date the title was borrowed on.");
        }        
    }

    /**
     * The name of the title borrowed.
     * @return The name of the title borrowed.
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * Sets The name of the title borrowed.
     * @param titleName The name of the title borrowed.
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }

    /**
     * gets The International Standard Book Number of the title borrowed.
     * @return The International Standard Book Number of the title borrowed.
     */
    public String getTitleIsbn() {
        return titleIsbn;
    }

    /**
     * Sets The International Standard Book Number of the title borrowed.
     * @param titleIsbn The International Standard Book Number of the title borrowed.
     */
    public void setTitleIsbn(String titleIsbn) {
        this.titleIsbn = titleIsbn;
    }

    /**
     * Gets the unique identifier of the user who borrowed this title on loan.
     * @return The unique identifier of the user who borrowed this title on loan.
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets The unique identifier of the user who borrowed this title on loan.
     * @param userID The unique identifier of the user who borrowed this title on loan.
     */
    public void setUserID(int userID) {
        this.userID = userID;
    }

    /**
     * Gets the name of the user who borrowed this title on loan.
     * @return The name of the user who borrowed this title on loan.
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the name of the user who borrowed this title on loan.
     * @param userName The name of the user who borrowed this title on loan.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Gets the email address of the user who borrowed this title on loan.
     * @return The email address of the user who borrowed this title on loan.
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * Sets the email address of the user who borrowed this title on loan.
     * @param userEmail The email address of the user who borrowed this title on loan.
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
   
    /**
     *
     * @return the number of days the title is overdue.
     */
    public int daysOverdue(){
        Date now = new Date();
        return (int)( ( now.getTime() - this.dateDue.getTime()) / (1000 * 60 * 60 * 24)); 
    }
        
    /**
     * Prints the details of this loan out to the screen.
     */
    public void display(){
        System.out.println(this.toString());
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.id;
        hash = 17 * hash + this.userID;
        hash = 17 * hash + (this.titleIsbn != null ? this.titleIsbn.hashCode() : 0);
        hash = 17 * hash + (this.dateBorrowed != null ? this.dateBorrowed.hashCode() : 0);
        hash = 17 * hash + (this.dateDue != null ? this.dateDue.hashCode() : 0);
        hash = 17 * hash + (this.dateReturned != null ? this.dateReturned.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Loan other = (Loan) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.userID != other.userID) {
            return false;
        }
        if ((this.titleIsbn == null) ? (other.titleIsbn != null) : !this.titleIsbn.equals(other.titleIsbn)) {
            return false;
        }
        if (this.dateBorrowed != other.dateBorrowed && (this.dateBorrowed == null || !this.dateBorrowed.equals(other.dateBorrowed))) {
            return false;
        }
        if (this.dateDue != other.dateDue && (this.dateDue == null || !this.dateDue.equals(other.dateDue))) {
            return false;
        }
        if (this.dateReturned != other.dateReturned && (this.dateReturned == null || !this.dateReturned.equals(other.dateReturned))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        String overdue = this.daysOverdue() > 0 ? "Over due by " + this.daysOverdue() + " days" : "" ;
        return String.format("%-13s\t%-60s\t%tB %<td, %<tY\t%tB %<td, %<tY\t%-20s",
                this.titleIsbn,
                this.titleName,
                this.dateBorrowed,
                this.dateDue,
                overdue);
    }
    
    public String toLongString(){
        String overdue = this.daysOverdue() > 0 ? "Over due by " + this.daysOverdue() + " days" : "" ;
        return String.format("%-13s\t%-60s\t%-20s\t%tB %<td, %<tY\t%tB %<td, %<tY\t%-20s",
                this.titleIsbn,
                this.titleName,
                this.userName,
                this.dateBorrowed,
                this.dateDue,
                overdue);        
    }
       
}
